name: Build for Android (ARMv7)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-linux-androideabi

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          add-to-path: true

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Build
        run: cargo ndk --target armv7-linux-androideabi --platform 21 build --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: il2cpp-dumper-armv7
          path: target/armv7-linux-androideabi/release/il2cpp_dumper
